//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace r6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detailorder
    {
        public int detailid { get; set; }
        public Nullable<int> orderid { get; set; }
        public Nullable<int> menuid { get; set; }
        public int qty { get; set; }
        public int price { get; set; }
        public string status { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Headorder Headorder { get; set; }
    }
}
