//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace r6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Headorder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Headorder()
        {
            this.Detailorders = new HashSet<Detailorder>();
        }
    
        public int orderid { get; set; }
        public Nullable<int> employeeid { get; set; }
        public Nullable<int> memberid { get; set; }
        public System.DateTime date { get; set; }
        public string payment { get; set; }
        public string bank { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detailorder> Detailorders { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Member Member { get; set; }
    }
}
